"""Created lot status field

Revision ID: ada8a1897f1c
Revises: aa28f1f9a9cd
Create Date: 2025-08-15 00:39:39.434931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ada8a1897f1c'
down_revision: Union[str, Sequence[str], None] = 'aa28f1f9a9cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lots', sa.Column('status', sa.Enum('running', 'finished', name='lotstatus', native_enum=False), server_default='running', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lots', 'status')
    # ### end Alembic commands ###
