services:
  db:
    build:
      context: ..
      dockerfile: ./docker/Dockerfile-mysql
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: myuser
      MYSQL_PASSWORD: admin
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql

  app:
    environment:
      DB_ENGINE: mysql

volumes:
  mysqldata: